# video input
input     : "/dev/video0"
win_input : "/dev/video0"

zed_camera : true

#cfg input
cfg_input : "../tests/darknet/cfg/yolo4.cfg"
cfg_win_input : "..\\..\\..\\tests\\darknet\\cfg\\yolo4.cfg"

#name input
name_input : "../tests/darknet/names/coco.names"
name_win_input : "..\\..\\..\\tests\\darknet\\names\\coco.names"

# network config
net         : "yolo4_fp32.rt"
ntype       : 'y'
n_classes   : 80
n_batch     : 1
conf_thresh : 0.3

# demo config
show  : true
save  : true

